package com.javacodegraph.model.declaration;

import com.javacodegraph.model.Node;
import com.javacodegraph.model.NodeIdGenerator;
import com.javacodegraph.model.Position;

import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import java.util.Set;

/**
 * Represents a class or interface declaration in Java source code.
 * 
 * Properties:
 * - name: The simple class name (e.g., "Calculator")
 * - qualified_name: The fully qualified name (e.g., "com.example.Calculator")
 * - modifiers: Set of modifiers (public, private, static, final, etc.)
 * - superclass: The fully qualified name of the superclass, or null
 * - interfaces: List of fully qualified interface names
 * - is_interface: true if this is an interface
 * - is_enum: true if this is an enum
 * - file: The source file path
 * - start/end: Position in source file
 */
public class ClassNode extends DeclarationNode {
    
    private final Set<String> modifiers;
    private final String superclass;
    private final List<String> interfaces;
    private final boolean isInterface;
    private final boolean isEnum;
    
    /**
     * Creates a new class node.
     * 
     * @param id the unique ID (generated by NodeIdGenerator)
     * @param name the simple class name
     * @param qualifiedName the fully qualified class name
     * @param modifiers the set of modifiers
     * @param superclass the fully qualified name of the superclass, or null
     * @param interfaces the list of fully qualified interface names
     * @param isInterface true if this is an interface
     * @param isEnum true if this is an enum
     * @param file the source file path
     * @param startPosition the start position in the file
     * @param endPosition the end position in the file
     */
    public ClassNode(String id, String name, String qualifiedName, 
                     Set<String> modifiers, String superclass, List<String> interfaces,
                     boolean isInterface, boolean isEnum, 
                     Path file, Position startPosition, Position endPosition) {
        super(id, name, qualifiedName, file, startPosition, endPosition);
        this.modifiers = modifiers != null ? Set.copyOf(modifiers) : Set.of();
        this.superclass = superclass;
        this.interfaces = interfaces != null ? List.copyOf(interfaces) : List.of();
        this.isInterface = isInterface;
        this.isEnum = isEnum;
    }
    
    @Override
    public String getType() {
        return Node.TYPE_CLASS;
    }
    
    /**
     * Returns the set of modifiers for this class.
     */
    public Set<String> getModifiers() {
        return Collections.unmodifiableSet(modifiers);
    }
    
    /**
     * Returns true if this class has the specified modifier.
     */
    public boolean hasModifier(String modifier) {
        if (modifier == null || modifier.isBlank()) {
            return false;
        }
        return modifiers.contains(modifier);
    }
    
    /**
     * Returns the fully qualified name of the superclass, or null if none.
     */
    public String getSuperclass() {
        return superclass;
    }
    
    /**
     * Returns true if this class has a superclass.
     */
    public boolean hasSuperclass() {
        return superclass != null && !superclass.isBlank();
    }
    
    /**
     * Returns the list of fully qualified interface names that this class implements.
     */
    public List<String> getInterfaces() {
        return Collections.unmodifiableList(interfaces);
    }
    
    /**
     * Returns true if this is an interface.
     */
    public boolean isInterface() {
        return isInterface;
    }
    
    /**
     * Returns true if this is an enum.
     */
    public boolean isEnum() {
        return isEnum;
    }
    
    /**
     * Returns true if this class is abstract.
     */
    public boolean isAbstract() {
        return modifiers.contains("abstract");
    }
    
    /**
     * Returns true if this class is final.
     */
    public boolean isFinal() {
        return modifiers.contains("final");
    }
    
    /**
     * Returns true if this class is public.
     */
    public boolean isPublic() {
        return modifiers.contains("public");
    }
    
    /**
     * Returns true if this class is private.
     */
    public boolean isPrivate() {
        return modifiers.contains("private");
    }
    
    /**
     * Returns true if this class is protected.
     */
    public boolean isProtected() {
        return modifiers.contains("protected");
    }
    
    /**
     * Returns true if this class is static (nested class).
     */
    public boolean isStatic() {
        return modifiers.contains("static");
    }
    
    /**
     * Returns the package name of this class.
     */
    public String getPackageName() {
        if (qualifiedName == null || qualifiedName.isBlank()) {
            return null;
        }
        int lastDot = qualifiedName.lastIndexOf('.');
        if (lastDot < 0) {
            return ""; // Default package
        }
        return qualifiedName.substring(0, lastDot);
    }
}
